---
- hosts: app_servers
  remote_user: root
  tasks:
     # Boilerplate stuff
    apt: upgrade_cache=yes
    apt: upgrade=yes
    apt: upgrade=dist
     # End boilerplate stuff
  	apt: name={{ items }} state=present
  	with_items:
  	  - postgresql #database server
  	  - postgresql-server-dev-9.3 #hooks for psycopg2
  	  - docker.io #docker for eventual expansion
          - libffi-dev #req for cffi which is a req for bcrypt
    	  - python-dev #req for bcrypt compilation as <#include Python.h> is in there
	  - python-virtualenv #obvious virtualenv stuff
  	  - htop #boilerplate stuff
  	  - tmux
  	  - slurm
  	  - mtr
  	  - rsync
  	  - screen
  	  - iftop
  	  - iotop
	  - git-core
          - build-essential
  	  - vim #end boilerplate stuff
    shell: echo "unbind C-b\nset -g prefix C-a\nbind C-a send-prefix" >> ~/.tmux.conf #make tmux hotkey sane
    shell: git clone https://github.com/Aeolus0/Flask-apps.git Flask-apps 
    shell: virtualenv Flask-apps/Flask-apps-venv/
