---
- hosts: app_servers
  remote_user: root
  tasks:
  	apt: name={{ items }} state=present
  	with_items:
  	  - postgresql #database server
  	  - postgresql-devel #hooks for psycopg2
  	  - docker.io #docker for eventual expansion
  	  - htop #boilerplate stuff
  	  - tmux
  	  - slurm
  	  - mtr
  	  - rsync
  	  - screen
  	  - iftop
  	  - iotop
  	  - vim #end boilerplate stuff


