---
- hosts: localhost
  connection: local
  tasks:
  	apt: name={{ items }} state=present
  	with_items:
  	  - postgresql-server-dev-9.3 #hooks for psycopg2
	  - postgresql-client-9.3 #psql command line
          - libffi-dev #req for cffi which is a req for bcrypt
          - python-pip
       	  - python-dev #req for bcrypt compilation as <#include Python.h> is in there
          - build-essential
    
